import pg from "pg";
import { AsyncLocalStorage } from "node:async_hooks";
import { npcs, evidence, lots } from "./content.js";
// Keep aggregate counts as numbers to preserve the API's numeric fields.
pg.types.setTypeParser(20, Number);
const schema = `

 CREATE TABLE IF NOT EXISTS players(id TEXT PRIMARY KEY,name TEXT NOT NULL,contact TEXT UNIQUE NOT NULL,password TEXT NOT NULL,payment TEXT DEFAULT 'pending',checked_in INTEGER DEFAULT 0,coins INTEGER DEFAULT 0 CHECK(coins>=0),group_id INTEGER DEFAULT 1,created_at TEXT DEFAULT (CURRENT_TIMESTAMP::text));
 CREATE TABLE IF NOT EXISTS characters(player_id TEXT PRIMARY KEY REFERENCES players(id),name TEXT,english TEXT,profession TEXT,skill TEXT,faction TEXT DEFAULT 'croft',story TEXT,secret TEXT,npc_id TEXT,status TEXT DEFAULT 'pending',motive TEXT);
 CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,role TEXT,user_id TEXT,expires BIGINT);
 CREATE TABLE IF NOT EXISTS settings(id INTEGER PRIMARY KEY CHECK(id=1),phase INTEGER DEFAULT 1,capacity INTEGER DEFAULT 40,price INTEGER DEFAULT 189,voting INTEGER DEFAULT 0);
 INSERT INTO settings(id) VALUES(1) ON CONFLICT DO NOTHING;
 CREATE TABLE IF NOT EXISTS npcs(id TEXT PRIMARY KEY,name TEXT,english TEXT,role TEXT,bio TEXT,secret TEXT);
 CREATE TABLE IF NOT EXISTS clues(id TEXT PRIMARY KEY,title TEXT,area TEXT,skill TEXT,dc INTEGER,body TEXT,detail TEXT,category TEXT,phase INTEGER DEFAULT 3);
 CREATE TABLE IF NOT EXISTS unlocks(player_id TEXT REFERENCES players(id),clue_id TEXT REFERENCES clues(id),created_at TEXT DEFAULT (CURRENT_TIMESTAMP::text),PRIMARY KEY(player_id,clue_id));
 CREATE TABLE IF NOT EXISTS checks(group_id INTEGER,area TEXT,roll INTEGER,bonus INTEGER,created_at TEXT DEFAULT (CURRENT_TIMESTAMP::text),PRIMARY KEY(group_id,area));
 CREATE TABLE IF NOT EXISTS ledger(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,player_id TEXT REFERENCES players(id),amount INTEGER,reason TEXT,created_at TEXT DEFAULT (CURRENT_TIMESTAMP::text));
 CREATE TABLE IF NOT EXISTS missions(id TEXT PRIMARY KEY,player_id TEXT REFERENCES players(id),title TEXT,npc_id TEXT,reward INTEGER,status TEXT DEFAULT 'pending');
 CREATE TABLE IF NOT EXISTS lots(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,title TEXT,start_price INTEGER,description TEXT,effect TEXT,status TEXT DEFAULT 'waiting',bid INTEGER DEFAULT 0,bidder TEXT REFERENCES players(id));
 CREATE TABLE IF NOT EXISTS bids(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,lot_id INTEGER REFERENCES lots(id),player_id TEXT REFERENCES players(id),amount INTEGER,created_at TEXT DEFAULT (CURRENT_TIMESTAMP::text));
 CREATE TABLE IF NOT EXISTS inventory(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,player_id TEXT REFERENCES players(id),lot_id INTEGER UNIQUE REFERENCES lots(id),used INTEGER DEFAULT 0);
 CREATE TABLE IF NOT EXISTS votes(player_id TEXT PRIMARY KEY REFERENCES players(id),suspect TEXT,motive TEXT,means TEXT,opportunity TEXT,decision TEXT,created_at TEXT DEFAULT (CURRENT_TIMESTAMP::text));
 CREATE TABLE IF NOT EXISTS events(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,title TEXT,body TEXT,created_at TEXT DEFAULT (CURRENT_TIMESTAMP::text));
 CREATE TABLE IF NOT EXISTS audit(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,actor TEXT,action TEXT,created_at TEXT DEFAULT (CURRENT_TIMESTAMP::text));`;

export async function openPostgres(connectionString) {
  const pool = new pg.Pool({
    connectionString,
    max: 3,
    idleTimeoutMillis: 30000,
    connectionTimeoutMillis: 5000,
    application_name: "alsj_booking",
  });
  pool.on("error", (error) =>
    console.error("PostgreSQL connection error:", error.message),
  );
  const scope = new AsyncLocalStorage();
  const query = (text, values) =>
    (scope.getStore() || pool).query(text, values);
  const translate = (sql) => {
    let index = 0;
    const ignore = /^INSERT OR IGNORE INTO /i.test(sql);
    return (
      sql
        .replace(/^INSERT OR IGNORE INTO /i, "INSERT INTO ")
        .replace(/\?/g, () => "$" + ++index) +
      (ignore ? " ON CONFLICT DO NOTHING" : "")
    );
  };
  const db = {
    prepare(sql) {
      const text = translate(sql);
      return {
        async get(...values) {
          return (await query(text, values)).rows[0];
        },
        async all(...values) {
          return (await query(text, values)).rows;
        },
        async run(...values) {
          const r = await query(text, values);
          return { changes: r.rowCount };
        },
      };
    },
    async transaction(fn) {
      if (scope.getStore())
        throw new Error("Nested transactions are unsupported");
      const client = await pool.connect();
      try {
        await client.query("BEGIN");
        // Serialize game mutations across requests and application instances.
        // The 40-player game needs only a small pool; this protects capacity,
        // duplicate rewards, auction reservations, and exactly-once settlement.
        await client.query("SELECT pg_advisory_xact_lock(619031206)");
        const result = await scope.run(client, fn);
        await client.query("COMMIT");
        return result;
      } catch (error) {
        await client.query("ROLLBACK");
        throw error;
      } finally {
        client.release();
      }
    },
    close() {
      return pool.end();
    },
  };
  try {
    await db.transaction(async () => {
      await query(schema);
      const seed = async (sql, rows) => {
        for (const row of rows) await db.prepare(sql).run(...row);
      };
      await seed("INSERT OR IGNORE INTO npcs VALUES(?,?,?,?,?,?)", npcs);
      await seed(
        "INSERT OR IGNORE INTO clues(id,title,area,skill,dc,body,detail,category) VALUES(?,?,?,?,?,?,?,?)",
        evidence,
      );
      await seed(
        "INSERT OR IGNORE INTO lots(id,title,start_price,description,effect) VALUES(?,?,?,?,?)",
        lots.map((l, i) => [i + 1, ...l]),
      );
    });
    return db;
  } catch (error) {
    await pool.end();
    throw error;
  }
}
